README.md

The aim of this PR is to create the first version of the Readme file which includes a description of the website contents.

Create the first version of the Readme file

---

.gitignore
LICENSE
README.md

In this PR we have changed the license from CPL 2.0 to GPL 3.0. Moreover, the .gitignore file has been created.

Change technical files

---

documentation/index.rst
documentation/seminars.rst

The aim of this PR is to create file with the seminars performed in the group.

Add the seminars file

---

documentation/journal_papers/DDSNCUC_TPWRS.rst
documentation/journal_papers/index.rst
documentation/working_papers.rst

The aim of this PR is to update the details of the recent published paper "Data-Driven Screening of Network Constraints for Unit Commitment".

Update the details of the new journal paper

---

documentation/journal_papers/DDSNCUC_TPWRS.rst

The aim of this PR in to include a summary of the main results and conclusions achieved in the new published paper "Data-Driven Screening of Network Constraints for Unit Commitment".

Fill the section main results of the recent-published paper

---

documentation/index.rst

Lisa added to developers

---

documentation/journal_papers/BIGM_TPWRS.rst
documentation/journal_papers/index.rst

Text corrected and paper links to open access added

changes 09/09

---

documentation/journal_papers/DDSNCUC_TPWRS.rst
documentation/journal_papers/NVWIND_TPWRS.rst
documentation/journal_papers/TAUC_TPWRS.rst

updates to cites and open access pdfs added

updating links and new cites

---

documentation/conference_papers/index.rst
documentation/index.rst
documentation/journal_papers/index.rst

changes to wording

---

documentation/working_papers.rst

removing reference to journals

working papers

---

documentation/journal_papers/AERADOAEV_TOSG.rst
documentation/journal_papers/DDSNCUC_TPWRS.rst

Changed Open Access pdfs to clickable links rather than opening in drive

Update links to pdf

---

documentation/journal_papers/AERADOAEV_TOSG.rst
documentation/journal_papers/BIGM_TPWRS.rst
documentation/journal_papers/NVWIND_TPWRS.rst
documentation/journal_papers/TAUC_TPWRS.rst

updating all pdf open access to pdf docs not drive

updating pdfs

---

documentation/contributions_in_conferences.rst

corrections

---

documentation/index.rst
documentation/seminars.rst

conferences update

---

documentation/contributions_in_conferences.rst

adding latest cons informs and autumn school

adding conferences

---

documentation/journal_papers/MMAFSNVMC_TPWRS.rst
documentation/journal_papers/index.rst
documentation/working_papers.rst

adding latest journal accepted

adding journal

---

documentation/working_papers.rst

adding working paper

---

documentation/journal_papers/index.rst

restoring toctree to journal papers

retoring toctree

---

documentation/working_papers.rst

adding latest paper to working papers

adding to working papers

---

documentation/journal_papers/IOKRAPFBFEV_TPWRS.rst
documentation/journal_papers/index.rst

adding recent titles to index and changing order of months

adding to index

---

documentation/working_papers.rst

adding latest preprints to working papers

updating working papers

---

documentation/working_papers.rst

adding code to working papers

---

documentation/journal_papers/CDCNSFUCP_TPWRS.rst

adding new pdf

---

documentation/contributions_in_conferences.rst

adding latest conferences

---

documentation/OASYS_seminar_series.rst

more presentations and link to symposium

Adding oasys seminars

---

documentation/OASYS_seminar_series.rst
documentation/contributions_in_conferences.rst
documentation/journal_papers/CDCNSFUCP_TPWRS.rst
documentation/journal_papers/DROPFWCI_EJOR.rst
documentation/journal_papers/HDFTAGSM_QE.rst
documentation/journal_papers/PNDTSEGS_ORP.rst
documentation/journal_papers/index.rst
documentation/working_papers.rst

adding latest papers, conferences and seminars. Also passing working papers to published and adding new working papers. Updating early access papers with publishing information

adding latest papers, updating conferences and seminars
